name: Publish container
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  publish-singularity-container:
    env:
      SINGULARITY: 1
    strategy:
      matrix:
        runner: [ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Clone Github Repo Action
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Install singularity
        run: sudo apt-get install -y singularity-container

      - name: Get container tag
        run: |
          TAG=$(cat bin/.container-tag)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Get container from cache
        id: cache-sif
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: .singularity/image.sif
          key: ${{ hashFiles('container.def', 'bin/.container-tag') }}

      - name: Get gems and node files from cache
        id: cache-bundle-npm
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            .home/.gems
            node_modules
          key: ${{ hashFiles('Gemfile.lock') }}-${{ hashFiles('package-lock.json') }}

      - if: ${{ steps.cache-sif.outputs.cache-hit != 'true' }}
        name: Build container
        run: ./bin/build_container

      - name: Upload singularity container
        run: |
          apptainer registry login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }} oras://docker.io
          apptainer push .singularity/image.sif oras://docker.io/riscvintl/spec-generator:${{ env.TAG }}

  publish-docker-container:
    env:
      DOCKER: 1
    runs-on: ubuntu-24.04
    steps:
      - name: Clone Github Repo Action
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1

      - name: Get container tag
        run: |
          TAG=$(cat bin/.container-tag)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build and push multi-platform image
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        with:
          push: true
          file: ./.devcontainer/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: riscvintl/udb:${{ env.TAG }}
