name: Update container.def

on:
  pull_request:
    paths:
      - .devcontainer/Dockerfile

permissions:
  contents: write

jobs:
  update-container-def:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          # Need to specify head_ref so that the action can push to the PR branch
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Update container.def
        run: uvx spython recipe .devcontainer/Dockerfile > container.def

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add container.def
          # Only commit if there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Update container.def"
            git push
          else
            echo "No changes to commit."
          fi
